### ISSUE TITLE
Bad performance with huge ceil value

### ISSUE THREAD

**Issue by ratskrspr** [danisss9/ngx-slider#5]
Hey there! Thanks a lot for forking the project. 🚀

We use the slider in our application to let the user select one of 86400 seconds and with ceil values that large, the browser needs to work for a long time before it displays the page. It used to work with the original implementation.

Repro:
`<ngx-slider [options]="{ ceil: 86400 }"></ngx-slider>`

**Comment by danisss9** [comment]
I did not change anything on how ceil works. Could be a result of a newer Angular version or even Angular Ivy .

Will Investigate

**Comment by ratskrspr** [comment]
Thanks for looking into it! We further investigated the changes and the thing we suspect is the removal of ```ChangeDetectionStrategy.OnPush```.

To elaborate further: after a few minutes the tab becomes responsive again until you try to adjust the slider value. Then the tab becomes unresponsive again. It also seems to scale with the ceil value: Larger ceil value -> longer waiting time.

**Comment by NatanCoralogix** [comment]
I also have the same issue!
Im using angular 15

**Comment by NatanCoralogix** [comment]
@danisss9 i just checked, and it doesn't fix the issue :( 
we are passing high values - 10429866 for example and the UI is stuck because of it.
in old package it doesn't happen

**Comment by danisss9** [comment]
@NatanCoralogix can you create a example with the problem in codeSandbox or something similar?

**Comment by NatanCoralogix** [comment]
The best i can do is share a screenshot.
as u can see we have many elements in the screen.
but the problem is from the slider itself, once the value is set to ~10000000 the screen will freeze for 2 min or so

![image](https://github.com/danisss9/ngx-slider/assets/110969383/5a2cb49b-0da7-4c35-9395-45691af3cefa)

**Comment by NatanCoralogix** [comment]
i  think it will be easy to reproduce.
create a simple ngfor of items with a scroller ( so u can scroll up and down and feel the performance). start the slider with a low value of 1000
then change it dynamically to  10000000
try to scroll

**Comment by NatanCoralogix** [comment]
@danisss9 there you go

https://stackblitz.com/edit/angular-74vxas?file=src/main.ts

**Comment by NatanCoralogix** [comment]
Hi, and lead on this?
sorry for pushing, just want to know if to wait for it
thanks for effort

**Comment by NatanCoralogix** [comment]
same for us :(

**Comment by trckndrsch** [comment]
We had the same issue and the high `ceil` value does not seem to be the problem but the large number of steps. So a workaround might be to increase the `step` value in the options if you have a large difference between `floor` and `ceil`.

In our case we had a logarithmic scale, so setting a high `step` value was not desirable on the low end of the slider. Instead we set the `stepsArray` option instead of `floor`, `ceil` and `step` and computed the logarithmic steps ourselves. For up to a few hundred steps the performance of the slider seems to be okay.

**Comment by fidian** [comment]
This turns out to be due to the large number of ticks and change detection. When a large number of ticks is added to `this.ticks`, the change detector appears to run through all of the values. To avoid this behavior and not show any ticks, simply add `ticksArray: []` to the options object. The ticks array is generated even when `showTicks: false` is configured, so this appears to be the best way to make the component faster.

Working demo with a minimum of 0, maximum of 6,000,000, and the ticks are overridden with an empty array:
https://codesandbox.io/p/sandbox/hardcore-haze-46cgft?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A1%2C1

The problem we had with mat-slider is that it did not update fast enough, so moving the handle with an average mouse speed caused it to not update. Also, accidentally leaving the track vertically and letting go caused weird issues if you drag the mouse over the handles again. Thus, no mat-slider for us.

**Comment by danisss9** [comment]
@fidian thank you for your investigation. I will update it so it does not calculate the ticksArray when showTicks is false.

About the update speed i don't know how i could improve it

The mouse drag issue could be because of the mouseEvent it uses but would need more investigation

**Comment by danisss9** [comment]
Copied to [main repo](https://github.com/angular-slider/ngx-slider/issues/366)
